version: "3"
services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    image: zhaopan/mdblog
    container_name: mdblog
    restart: always
    ports:
      - "80:8091"
#    volumes:
#      - /docker/blog-docs:/app/resources/blog-docs
    environment:
      - DOMAIN=<blog.website.com>
    command: /bin/sh /server.sh
